-- ACTORS
INSERT INTO "MOVIERENTAL"."ACTORS" (ID_ACTOR, FIRSTNAME, LASTNAME) VALUES ('1', 'Tom', 'Cruise');
INSERT INTO "MOVIERENTAL"."ACTORS" (ID_ACTOR, FIRSTNAME, LASTNAME) VALUES ('2', 'Brad', 'Pitt');
INSERT INTO "MOVIERENTAL"."ACTORS" (ID_ACTOR, FIRSTNAME, LASTNAME) VALUES ('3', 'Cameron', 'Diaz');

-- ACTORS_TO_MOVIES

-- DATA_MEDIUM
INSERT INTO "MOVIERENTAL"."DATA_MEDIUM" (ID_DATA_MEDIUM, NAME_DATA_MEDIUM) VALUES ('1', 'DVD');
INSERT INTO "MOVIERENTAL"."DATA_MEDIUM" (ID_DATA_MEDIUM, NAME_DATA_MEDIUM) VALUES ('2', 'Blu-ray');

-- DISCOUNTS
INSERT INTO "MOVIERENTAL"."DISCOUNTS" (ID_DISCOUNT, NAME_DISCOUNT, VALUE_DISCOUNT) VALUES ('1', 'GreatOffer', '10');

-- GENRES
INSERT INTO "MOVIERENTAL"."GENRES" (ID_GENRE, NAME_GENRE) VALUES ('1', 'Action');
INSERT INTO "MOVIERENTAL"."GENRES" (ID_GENRE, NAME_GENRE) VALUES ('2', 'Sci-fi');
INSERT INTO "MOVIERENTAL"."GENRES" (ID_GENRE, NAME_GENRE) VALUES ('3', 'Comedy');
INSERT INTO "MOVIERENTAL"."GENRES" (ID_GENRE, NAME_GENRE) VALUES ('4', 'Drama');

-- MOVIES
INSERT INTO "MOVIERENTAL"."MOVIES" (ID_MOVIE, TITLE, YEAR, THREE_DIMENSIONAL, CINEMA, ID_GENRE, ID_DATA_MEDIUM) VALUES ('1', 'Harry Potter and the Order of the Phoenix', '2007', '0', '0', '4', '1');
INSERT INTO "MOVIERENTAL"."MOVIES" (ID_MOVIE, TITLE, YEAR, THREE_DIMENSIONAL, CINEMA, ID_GENRE, ID_DATA_MEDIUM) VALUES ('2', 'Elle s''appelait Sarah ', '2010', '0', '0', '4', '1');
INSERT INTO "MOVIERENTAL"."MOVIES" (ID_MOVIE, TITLE, YEAR, THREE_DIMENSIONAL, CINEMA, ID_GENRE, ID_DATA_MEDIUM) VALUES ('3', 'Legacy', '2010', '1', '0', '2', '2');
INSERT INTO "MOVIERENTAL"."MOVIES" (ID_MOVIE, TITLE, YEAR, THREE_DIMENSIONAL, CINEMA, ID_GENRE) VALUES ('4', 'Transformers: Dark of the Moon', '2011', '0', '1', '1');

-- ORDERS

-- ORDERS_TO_MOVIES

-- RESERVATIONS

-- RESERVATIONS_TO_MOVIES

-- ROLES
INSERT INTO "MOVIERENTAL"."ROLES" (ID_ROLE, NAME_ROLE) VALUES ('1', 'ADMIN');
INSERT INTO "MOVIERENTAL"."ROLES" (ID_ROLE, NAME_ROLE) VALUES ('2', 'USER');
INSERT INTO "MOVIERENTAL"."ROLES" (ID_ROLE, NAME_ROLE) VALUES ('3', 'SYSTEM');

-- USERS
INSERT INTO "MOVIERENTAL"."USERS" (ID_USER, NICK, FIRSTNAME, LASTNAME, PASSWORD, CITY, STREET_ADDRESS, "E-MAIL", TELEPHONE, CREDIT, REGISTER_DATE_TIME, ID_ROLE) VALUES ('1', 'admin', 'James', 'Cook', 'pass', 'London', 'Oxford Street', 'MOVIERENTAL@MOVIERENTAL.net', '421910789456', '0', TO_DATE('27-JUN-11', 'DD-MON-RR'), '1');
INSERT INTO "MOVIERENTAL"."USERS" (ID_USER, NICK, FIRSTNAME, LASTNAME, PASSWORD, CITY, STREET_ADDRESS, "E-MAIL", TELEPHONE, CREDIT, REGISTER_DATE_TIME, ID_ROLE) VALUES ('2', 'MOVIERENTAL', 'James', 'Cook', 'pass', 'London', 'Oxford Street', 'MOVIERENTAL@MOVIERENTAL.net', '421911754456', '5.68', TO_DATE('27-JUN-11', 'DD-MON-RR'), '2');

COMMIT;
/